version: '3.8'

services:
  cl-lighthouse:
    image: ethpandaops/lighthouse:stable
    command: 
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/data/lighthouse/beacon-data
      - --disable-enr-auto-update
      - --enr-address=172.16.0.15
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --listen-address=0.0.0.0
      - --port=9000
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --http-allow-sync-stalled
      - --slots-per-restore-point=32
      - --disable-packet-filter
      - --execution-endpoints=http://el-geth:8551
      - --jwt-secrets=/jwt/jwtsecret
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --enable-private-discovery
      - --testnet-dir=/network-configs
      - --boot-nodes=enr:-MS4QMK2QF0OYCPH_13IWhnqtcuC54gqM4xyZfiyq-t0Kp8MUWQN5_zj0c8poXdGZ6wjftMIyXWkg2F5AFW5I-rYQT8Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDYTi7gYAAAOADh9QUAAAAAgmlkgnY0gmlwhKwQAAyEcXVpY4IjKYlzZWNwMjU2azGhA5msOhRiZPTAI1W2ZERusCjKu8aWYfruhE6uXDTBwgtuiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
    networks:
      - network1
    volumes:
      - ./cl/data/lighthouse/beacon-data:/data/lighthouse/beacon-data
      - ./cl/jwt:/jwt
      - ./cl/network-configs:/network-configs
    ports:
      - "5052:5052"
      - "4000:4000"
      - "9000:9000"
    environment:
      - RUST_BACKTRACE=full
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GOPROXY=https://goproxy.primary.production.platform.ethpandaops.io
    restart: always
  
  el-geth:
    build:
      context: .
      dockerfile: Dockerfile.geth
    command: 
      - --networkid=12020498 
      - --verbosity=3 
      - --http 
      - --http.addr=0.0.0.0 
      - --http.vhosts=* 
      - --http.corsdomain=* 
      - --http.api=admin,engine,net,eth,web3,debug 
      - --ws 
      - --ws.addr=0.0.0.0 
      - --ws.port=8546 
      - --ws.api=admin,engine,net,eth,web3,debug 
      - --ws.origins=* 
      - --allow-insecure-unlock 
      - --nat=extip:172.16.0.11 
      - --authrpc.port=8551 
      - --authrpc.addr=0.0.0.0 
      - --authrpc.vhosts=* 
      - --authrpc.jwtsecret=/jwt/jwtsecret 
      - --syncmode=full 
      - --gcmode=archive
      - --rpc.allow-unprotected-txs 
      - --metrics 
      - --metrics.addr=0.0.0.0 
      - --metrics.port=9001 
      - --discovery.port=30303 
      - --port=30303 
      - --bootnodes=enode://a868aec78f3bfd499e7d9aef80dd36b410c37d964e83ffb202444bb2acc23ccb3c370cfbcecdf96b42ab19f469a831df12ea9321711ea6efd21d97b20943a3b6@172.16.0.10:30303
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "9001:9001"
    volumes:
      - ./el/jwt:/jwt
      - el-geth:/root/.ethereum
    networks:
      - network1

    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

volumes:
  el-geth:

networks:
  network1:
    name: kt-lummio-network
    external: true
